from pydantic import BaseModel
from typing import List, Optional

# ---------------------------------------------------------
# ObjectTracking.tsx Schemas
# ---------------------------------------------------------

class TrackedObject(BaseModel):
    """
    Schema representing a tracked object over time in the video feed.
    Matches the mock data structure in ObjectTracking.tsx.
    """
    id: str                 # Unique identifier for the tracked object (e.g., "P001")
    type: str               # Class/Label of the object (e.g., "Person", "Vehicle")
    status: str             # Tracking status (e.g., "Active", "Lost")
    timeInFrame: str        # Formatted string showing time tracked (e.g., "45s")
    path: List[List[float]] # Array of [x, y] coordinates representing trajectory history
    color: str              # Hex color assigned to the bounding box/path (e.g., "#FF0040")
    currentPos: List[float] # Current center/position [x, y] in absolute pixel coordinates
    promptMatch: str        # Description matched via VLM prompt (e.g., "person in red shirt")


# ---------------------------------------------------------
# VisionLanguage.tsx Schemas
# ---------------------------------------------------------

class QueryObject(BaseModel):
    """
    Schema representing an individual detected object relevant to a query.
    Matches the objects array within the query result mock in VisionLanguage.tsx.
    """
    type: str               # Object class (e.g., "Person")
    id: str                 # Object ID (e.g., "P001")
    bbox: List[float]       # Bounding box [x, y, w, h] in absolute pixel coordinates


class QueryResult(BaseModel):
    """
    Schema representing the result of a natural language query on the video feed.
    Matches the mock result object in VisionLanguage.tsx.
    """
    id: int                 # Unique ID / Timestamp for the query result
    query: str              # The original prompt sent by the user
    answer: str             # The natural language summary/answer generated by the backend
    timestamp: str          # Time indicator string (e.g., "Just now")
    objects: List[QueryObject] # List of objects relevant to the answer


# ---------------------------------------------------------
# VisionLanguage.tsx (Streaming Log) Schemas
# ---------------------------------------------------------

class StreamSegment(BaseModel):
    """
    Schema representing a rich text chunk within a terminal feed log.
    """
    text: str               # The actual text segment
    color: Optional[str] = None # Optional hex color (e.g., "#FFFFFF")


class StreamLog(BaseModel):
    """
    Schema representing a live VLM stream log entry.
    Matches the mock terminal feed in VisionLanguage.tsx.
    """
    frame: str              # Frame number as string (e.g., "0312")
    opacity: float          # Fading effect for older logs (e.g., 0.78)
    segments: List[StreamSegment] # Rich text chunks
